// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookshop.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PageCount            int32    `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_19d7f94918d35a25, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

func (m *Book) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type GetBookListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookListRequest) Reset()         { *m = GetBookListRequest{} }
func (m *GetBookListRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookListRequest) ProtoMessage()    {}
func (*GetBookListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19d7f94918d35a25, []int{1}
}

func (m *GetBookListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookListRequest.Unmarshal(m, b)
}
func (m *GetBookListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookListRequest.Marshal(b, m, deterministic)
}
func (m *GetBookListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookListRequest.Merge(m, src)
}
func (m *GetBookListRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookListRequest.Size(m)
}
func (m *GetBookListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookListRequest proto.InternalMessageInfo

type GetBookListResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookListResponse) Reset()         { *m = GetBookListResponse{} }
func (m *GetBookListResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookListResponse) ProtoMessage()    {}
func (*GetBookListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19d7f94918d35a25, []int{2}
}

func (m *GetBookListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookListResponse.Unmarshal(m, b)
}
func (m *GetBookListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookListResponse.Marshal(b, m, deterministic)
}
func (m *GetBookListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookListResponse.Merge(m, src)
}
func (m *GetBookListResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookListResponse.Size(m)
}
func (m *GetBookListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookListResponse proto.InternalMessageInfo

func (m *GetBookListResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "Book")
	proto.RegisterType((*GetBookListRequest)(nil), "GetBookListRequest")
	proto.RegisterType((*GetBookListResponse)(nil), "GetBookListResponse")
}

func init() { proto.RegisterFile("bookshop.proto", fileDescriptor_19d7f94918d35a25) }

var fileDescriptor_19d7f94918d35a25 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x6d, 0x8a, 0x99, 0x82, 0x87, 0x49, 0x94, 0xa5, 0x22, 0x84, 0x9c, 0x72, 0x4a,
	0x21, 0xde, 0x3c, 0xd6, 0x43, 0x11, 0x3c, 0xe5, 0xe8, 0x45, 0x12, 0x19, 0xd2, 0xd0, 0xb2, 0xb3,
	0xee, 0xce, 0x16, 0xfc, 0xf7, 0xb2, 0x5b, 0x15, 0x45, 0x8f, 0xef, 0x63, 0xe6, 0x7d, 0xc3, 0xc0,
	0xe5, 0xc0, 0xbc, 0x77, 0x3b, 0x36, 0x8d, 0xb1, 0x2c, 0x5c, 0x31, 0xcc, 0x37, 0xcc, 0x7b, 0x2c,
	0x20, 0x95, 0x49, 0x0e, 0xa4, 0x92, 0x32, 0xa9, 0xb3, 0xee, 0x14, 0xf0, 0x1a, 0x16, 0xbd, 0x97,
	0x1d, 0x5b, 0x75, 0x1e, 0xf1, 0x67, 0xc2, 0x5b, 0x00, 0xd3, 0x8f, 0xf4, 0xf2, 0xca, 0x5e, 0x8b,
	0x9a, 0x95, 0x49, 0x9d, 0x76, 0x59, 0x20, 0x0f, 0x01, 0xe0, 0x0a, 0x2e, 0x0e, 0xbd, 0x1e, 0x7d,
	0x3f, 0x92, 0x9a, 0xc7, 0xc5, 0xef, 0x5c, 0x15, 0x80, 0x5b, 0x92, 0xe0, 0x7c, 0x9a, 0x9c, 0x74,
	0xf4, 0xe6, 0xc9, 0x49, 0xd5, 0x42, 0xfe, 0x8b, 0x3a, 0xc3, 0xda, 0x11, 0xde, 0x40, 0x1a, 0xef,
	0x55, 0x49, 0x39, 0xab, 0x97, 0x6d, 0xda, 0x84, 0x89, 0xee, 0xc4, 0xda, 0x2d, 0x64, 0x8f, 0xfa,
	0x48, 0x5a, 0xd8, 0xbe, 0xe3, 0x3d, 0x2c, 0x7f, 0x14, 0x60, 0xde, 0xfc, 0x95, 0xac, 0x8a, 0xe6,
	0x1f, 0x47, 0x75, 0xb6, 0xb9, 0x7a, 0xce, 0x1d, 0xd9, 0x23, 0xd9, 0xb5, 0x19, 0xd6, 0xd3, 0x57,
	0xe5, 0xb0, 0x88, 0x1f, 0xba, 0xfb, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x89, 0x8a, 0xf4, 0x33,
	0x01, 0x00, 0x00,
}
